name: 'Release Astro Editor'

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--bundles app,dmg'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Import Code-Signing Certificates
        if: matrix.platform == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Create API Key file
        if: matrix.platform == 'macos-latest'
        run: |
          # Create multiple potential locations for API key
          mkdir -p ./private_keys
          mkdir -p ./src-tauri/private_keys
          mkdir -p ~/private_keys
          
          # Create API key file with proper permissions in all locations
          echo "${{ secrets.APPLE_API_KEY_PATH }}" > ./private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          echo "${{ secrets.APPLE_API_KEY_PATH }}" > ./src-tauri/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          echo "${{ secrets.APPLE_API_KEY_PATH }}" > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          
          # Set proper permissions
          chmod 600 ./private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          chmod 600 ./src-tauri/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          chmod 600 ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          
          # Debug: List created files
          ls -la ./private_keys/ || echo "No ./private_keys/"
          ls -la ./src-tauri/private_keys/ || echo "No ./src-tauri/private_keys/"
          ls -la ~/private_keys/ || echo "No ~/private_keys/"

      - name: Build and release
        uses: tauri-apps/tauri-action@v0.5.22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tauri updater signing (separate from Apple signing)
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          # Apple notarization via API key (no password needed!)
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_PATH: ./private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
          APPLE_PROVIDER_SHORT_NAME: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: ${{ github.ref_name || inputs.version }}
          releaseName: 'Astro Editor ${{ github.ref_name || inputs.version }}'
          releaseBody: |
            ## 🚀 Astro Editor ${{ github.ref_name || inputs.version }}
            
            ### Installation Instructions
            - **macOS**: Download the `.dmg` file and drag to Applications folder
            
            ### Auto-Updates
            Existing users will receive automatic update notifications.
            
            **Full Changelog**: https://github.com/${{ github.repository }}/commits/${{ github.ref_name || inputs.version }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
